### ISSUE TITLE
membuat feature di halaman register

### ISSUE THREAD

**Issue by Lrini** [Lrini/sdhshop#11]

**Comment by Bennimaru09** [comment]
![image](https://github.com/Lrini/sdhshop/assets/131897381/ff8b4144-35e0-4aa3-9faa-c073f4d42993)


pak ini kan saya mau connect ke database pakai php. codenya gini su ko pak? soalnya saya baru belajar php jadi bingung bingung

![image](https://github.com/Lrini/sdhshop/assets/131897381/8643e02f-c892-4ddd-810a-a1c4a51ea234)
trus saya masukin file submit.php ke index php pakai code from action tu bisa atau tidak pak

**Comment by Lrini** [comment]
mantap bro.
coba push di staging biar pak perbaiki bro
