### ISSUE TITLE
membuat feature di halaman login

### ISSUE THREAD

**Issue by Lrini** [Lrini/sdhshop#19]

**Comment by MazmurBryan** [comment]
![image](https://github.com/Lrini/sdhshop/assets/94032400/cac99332-f5c9-4612-917c-6de79387de40)

![image](https://github.com/Lrini/sdhshop/assets/94032400/46f8149f-1c52-4295-93a6-cc9a6815a7cc)
pak ini scriptnya apakah sudah benar kah?

**Comment by MazmurBryan** [comment]
untuk css saya baru tambahn animasi dikit saja pak, untuk phpnya nanti integrasi ke database betul kah pak?

**Comment by MazmurBryan** [comment]
![image](https://github.com/Lrini/sdhshop/assets/94032400/8b53be34-cdd7-4e1b-bc4f-8f88ea9c100a)
tapi seperti ini pak

**Comment by MazmurBryan** [comment]
pak saya juga coba buat untuk registny supaya coba test login 
![image](https://github.com/Lrini/sdhshop/assets/94032400/ac995e1d-4a2f-4909-8152-900be7e88a3d)
![image](https://github.com/Lrini/sdhshop/assets/94032400/ea481924-7e94-4532-824e-2d399f89d131)
![image](https://github.com/Lrini/sdhshop/assets/94032400/a4be5fdb-c407-4c35-be33-dab97591c4e9)
![image](https://github.com/Lrini/sdhshop/assets/94032400/31910163-4169-4d45-90f3-f4fbce236740)

database untuk samain gimana pak?
